name: json_store
description: A simple, file-based NoSQL database for Dart applications, offering a FireStore-like API for persistent data storage using JSON files.
version: 1.0.0
repository: https://github.com/najeebagha/json_store

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  uuid: ^4.5.1
  path_provider: ^2.1.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
